# Generated by Django 6.0.2 on 2026-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='task_reports/', verbose_name='Отчёт/документ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('RETURNED', 'Возвращена'), ('DONE', 'Завершена')], default='NEW', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
