# Generated by Django 6.0.2 on 2026-02-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_report_file_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tasks', to='tracker.employee', verbose_name='Владелец задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий проверяющего'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('REVIEW', 'На проверке'), ('DONE', 'Завершена')], default='NEW', max_length=20, verbose_name='Статус задачи'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('assignee__isnull', True), models.Q(('owner', models.F('assignee')), _negated=True), _connector='OR'), name='prevent_owner_is_assignee'),
        ),
    ]
